// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaS1VYx8xVdP7ym9yyGJcc7lX6loXTCC8',
    appId: '1:551002621726:web:3350d961bd8d383ad4eb0f',
    messagingSenderId: '551002621726',
    projectId: 'quiz-52c30',
    authDomain: 'quiz-52c30.firebaseapp.com',
    storageBucket: 'quiz-52c30.firebasestorage.app',
    measurementId: 'G-3ZPS2VFE5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1uGRbXnv3DSy6Ljjjf40SjdfLPHtw2gk',
    appId: '1:551002621726:android:3e370d1588bfa470d4eb0f',
    messagingSenderId: '551002621726',
    projectId: 'quiz-52c30',
    storageBucket: 'quiz-52c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBE8eLjfa3NioELKiZcf2xNLvqruZs_sE',
    appId: '1:551002621726:ios:3b7aa2f5b5fc5269d4eb0f',
    messagingSenderId: '551002621726',
    projectId: 'quiz-52c30',
    storageBucket: 'quiz-52c30.firebasestorage.app',
    iosBundleId: 'com.example.secureQuiz',
  );
}
